config/routes.rb
Rails.application.routes.draw do
  resources :high_scores
  root 'high_scores#index' 	

end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
    respond_to do |format|
    	format.html
    	format.json
    end

  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        flash[:success] = 'High score was successfully created.' 
        format.html { redirect_to @high_score}
        format.json { render :show, status: :created, location: @high_score }
	format.js #create.js.erb
      else
	flash[:danger] = 'There was a problem creating the High score'
        format.html { render :new }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
	flash[:success] = 'High score was successfully updated.' 
        format.html { redirect_to @high_score}
        format.json { render :show, status: :ok, location: @high_score }
	format.js #create.js.erb
      else
	flash[:danger] = 'There was a problem updating the High score'
        format.html { render :edit }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      flash[:success] = 'High score was successfully destroyed.' 
      format.html { redirect_to high_scores_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_score_params
      params.require(:high_score).permit(:game, :score, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/views/high_scores/_form.html.erb
<%= form_for(@high_score, remote: true, html: {class: 'form-horizontal'}) do |f| %>
  <% if @high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @high_score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :game, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :game, class: 'form-control' %>
    </div>	 
  </div>
  <div class="field form-group">
    <%= f.label :score, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.number_field :score, class: 'form-control' %>
    </div>	
  </div>
  <div class="field form-group">
    <%= f.label :notes, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :notes, class: 'form-control' %>
    </div>	
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-xs' %>
    </div>
  </div>
<% end %>

app/views/high_scores/create.js.erb
$('#task-form').slideUp(350);

app/views/high_scores/edit.html.erb
<h1>Editing High Score</h1>

<%= render 'form' %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<ul class="nav nav-pils" role="tablist">
  <li class="active"><%= link_to 'View list', high_scores_path %></li>
  <li><%= link_to 'New HighScore', new_high_score_path %></li>
</ul>



<p id="notice"><%= notice %></p>

<h1>Listing High Scores</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Game</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @high_scores.each do |high_score| %>
      <tr>
	<td>
		<span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{high_score.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{high_score.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
			<%= high_score.game %>
		</span>
	</td>
        <td><%= high_score.score %></td>
	<td>
	<% if high_score.notes? %>
	
       	<!-- Button trigger modal -->
	<button class="btn btn-link" data-toggle="modal" data-target="#todo-<%= high_score.id %>-notes">
		View notes
	</button>

  <!-- Modal -->
	<div class="modal fade" id="todo-<%= high_score.id %>-notes" tabindex="-1" role="dialog" aria-labelledby="todo-<%= high_score.id %>-label" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="todo-<%= high_score.id %>-label">Notes</h4>
				</div>
				<div class="modal-body">
					<%= high_score.notes %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>

  <button type="button" class="btn btn-link has-popover" data-toggle="popover" title="Notes" data-content="<%= high_score.notes %>">View notes (popover)</button>
	<% end %>
        <td><%= link_to 'Show', high_score, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_high_score_path(high_score), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="task-form" style="display:none;"></div>
<br>

<%= link_to new_high_score_path, remote: true, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New HighScore
<% end %>

app/views/high_scores/new.html.erb
<ul class="nav nav-pils" role="tablist">
  <li><%= link_to 'View list', high_scores_path %></li>
  <li class="active"><%= link_to 'New HighScore', new_high_score_path %></li>
</ul>

<h1>New High Score</h1>

<%= render 'form' %>

app/views/high_scores/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @high_score.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @high_score.score %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @high_score.notes %>
</p>



<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navigation' %>


   <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>


</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Dave's Games</a>
    </div>
  </div>
</nav>